id: I753CFD89
legacy_id: P009114
ocr_import_info:
  bdrc_scan_id: W22177
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T04:39:10'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T20:52:27.296240+00:00'
last_modified: 2022-09-02 04:53:10.804391
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22177
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW22177
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཐུབ་བསྟན་ཡར་འཕེལ་དབང་པོ།
  author: ཐུབ་བསྟན་ཡར་འཕེལ་དབང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.6384519427880351
  ocr_word_median_confidence_index: 0.6700000166893005
quality: null
bases:
  I1KG10862:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10862
      total_pages: 730
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10862.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.7107404392816269
    legacy_id: v001
  I1KG10863:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10863
      total_pages: 858
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG10863.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.5930361254350325
    legacy_id: v002
  I1KG10864:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10864
      total_pages: 306
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG10864.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6242954056358854
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
