id: I753CFD89
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T04:41:35+00:00'
last_modified: '2022-06-08T08:43:18.131714+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22177
  title: གསུང་འབུམ། ཐུབ་བསྟན་ཡར་འཕེལ་དབང་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    56FF:
      image_group_id: I1KG10862
      title: ''
      total_pages: 730
      order: 1
      base_file: 56FF.txt
    0394:
      image_group_id: I1KG10863
      title: ''
      total_pages: 858
      order: 2
      base_file: 0394.txt
    '5225':
      image_group_id: I1KG10864
      title: ''
      total_pages: 306
      order: 3
      base_file: 5225.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
